import html2pdf from 'html2pdf.js';
import { Letter } from '../types/Letter';

export const generateLetterPDF = (letter: Letter) => {
  const formatDate = (date: Date) => {
    return date.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const htmlContent = `
    <div style="font-family: 'Roboto Mono', monospace; max-width: 600px; margin: 40px auto; padding: 40px; background: white;">
      <!-- Header -->
      <div style="text-align: center; border-bottom: 2px solid #e5e7eb; padding-bottom: 30px; margin-bottom: 40px;">
        <div style="font-size: 48px; margin-bottom: 10px;">${letter.emoji}</div>
        <h1 style="font-family: 'serif'; font-size: 32px; color: #581c87; margin: 0; line-height: 1.2;">
          ${letter.title}
        </h1>
        <div style="margin-top: 15px; color: #7c3aed; font-size: 14px;">
          <span style="background: #f3e8ff; padding: 4px 12px; border-radius: 12px; margin-right: 15px;">
            ${letter.label}
          </span>
          <span>${formatDate(letter.timestamp)}</span>
        </div>
      </div>

      <!-- Content -->
      <div style="line-height: 1.8; color: #374151; font-size: 16px; white-space: pre-wrap;">
        ${letter.content}
      </div>

      <!-- Footer -->
      <div style="margin-top: 50px; padding-top: 30px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px;">
        <p>Sealed with ${letter.emoji} • Generated by Sealya</p>
        <p style="margin-top: 5px;">A digital sanctuary for sealed emotions</p>
      </div>
    </div>
  `;

  const options = {
    margin: 0.5,
    filename: `${letter.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${letter.timestamp.getTime()}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { 
      scale: 2,
      useCORS: true,
      letterRendering: true,
    },
    jsPDF: { 
      unit: 'in', 
      format: 'a4', 
      orientation: 'portrait',
      compress: true
    }
  };

  return html2pdf().set(options).from(htmlContent).save();
};